server:
  port: 8001
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/coffeeshop_base"
    username: "postgres"
    password: "postgres"
  jpa:
    generate-ddl: true
  freemarker:
    expose-request-attributes: true
    suffix: .ftl
